spring:
  application:
    name: demo
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://1haoji:3306/hello_jpa?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: admin

  jpa:
    # 切换InnoDB引擎
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
decorator:
  datasource:
    p6spy:
      enable-logging: true
      # log-file: p6spy.log
      multiline: true
      logging: slf4j
      log-format: 执行SQL- 耗时 %(executionTime)ms | 类型 %(category) | connection%(connectionId) | %(sqlSingleLine);

logging:
  pattern:
    dateformat: yyyy-MMM-dd HH:mm:ss.SSS
  level:
    root: info
    org.hibernate: info
#    org.hibernate.type.descriptor.sql.BasicBinder: trace
#    org.hibernate.type.descriptor.sql.BasicExtractor: debug
#    org.hibernate.SQL: debug
#    org.hibernate.engine.QueryParameters: debug
#    org.hibernate.engine.query.HQLQueryPlan: debug
    org.springframework.web: error
    org.apache: info
    com.zaxxer.hikari: info